Attributes and the raw ndarray(s)
====

In [1]:
import numpy as np
import pandas as pd

index = pd.date_range('1/1/2000', periods=8)

s = pd.Series(np.random.randn(5), index=['a', 'b', 'c', 'd', 'e'])

df = pd.DataFrame(np.random.randn(8, 3), index=index,
                  columns=['A', 'B', 'C'])

wp = pd.Panel(np.random.randn(2, 5, 4), items=['Item1', 'Item2'],
              major_axis=pd.date_range('1/1/2000', periods=5),
              minor_axis=['A', 'B', 'C', 'D'])

C:\ProgramData\Anaconda3\lib\site-packages\IPython\core\interactiveshell.py:2961: FutureWarning: 
Panel is deprecated and will be removed in a future version.
The recommended way to represent these types of 3-dimensional data are with a MultiIndex on a DataFrame, via the Panel.to_frame() method
Alternatively, you can use the xarray package http://xarray.pydata.org/en/stable/.
Pandas provides a `.to_xarray()` method to help automate this conversion.

  exec(code_obj, self.user_global_ns, self.user_ns)


pandas objects have a number of attributes enabling you to access the metadata

pandas 对象有许多属性，使您能够访问元数据:

> - **shape**: gives the axis dimensions of the object, consistent with ndarray
> - Axis labels
>   - **Series**: *index* (only axis)
>   - **DataFrame**: *index* (rows) and *columns*
>   - **Panel**: *items*, *major_axis*, and *minor_axis*

Note, **these attributes can be safely assigned to**!

注意：**注意，可以安全地给这些属性分配值！**

In [2]:
df[:2]

A         B         C
2000-01-01  0.394674  0.433492  2.023796
2000-01-02 -0.528558 -0.402739 -0.930417

In [4]:
df.columns = [x.lower() for x in df.columns]
df

a         b         c
2000-01-01  0.394674  0.433492  2.023796
2000-01-02 -0.528558 -0.402739 -0.930417
2000-01-03  0.917812 -0.787132 -0.162575
2000-01-04  0.256214 -0.171129 -0.355904
2000-01-05  1.298942  0.735948 -0.207659
2000-01-06  0.896531  1.283653 -0.003820
2000-01-07  0.388685 -0.715222 -1.152511
2000-01-08  0.769418  1.378707  0.206160

To get the actual data inside a data structure, one need only access the **values** property:

要获取数据结构中的实际数据，只需访问** values **属性：

In [6]:
s.values

array([2.4867193 , 0.01745447, 0.14298012, 1.20575426, 0.59399626])

In [7]:
df.values

array([[ 0.39467431,  0.43349235,  2.02379618],
       [-0.528558  , -0.40273923, -0.93041671],
       [ 0.91781164, -0.78713182, -0.16257453],
       [ 0.25621413, -0.17112861, -0.35590385],
       [ 1.29894221,  0.73594835, -0.20765854],
       [ 0.89653072,  1.28365261, -0.0038204 ],
       [ 0.38868505, -0.71522216, -1.1525112 ],
       [ 0.76941786,  1.3787074 ,  0.20615985]])

In [8]:
wp.values

array([[[-0.17074669,  0.66851919, -1.53978767, -0.11472463],
        [ 0.63384452, -2.47289731, -1.7582439 , -0.14286273],
        [ 0.13781111, -0.67006671,  0.95351074, -0.56746184],
        [-0.27862113,  0.47679002, -1.46929364,  1.14373804],
        [-0.83308108,  1.16399997,  1.34573088, -1.39655571]],

       [[ 0.93904349, -1.09245451, -0.35381776, -0.97695504],
        [-1.83692393, -1.56439524,  1.46279797, -0.62253708],
        [ 1.14304908, -0.49556513, -1.15649517,  0.7763023 ],
        [-1.49528171,  0.07482871, -0.45071584, -0.79840014],
        [-0.04749522,  1.10373656,  1.78909911,  0.51019508]]])

If a DataFrame or Panel contains homogeneously-typed data, the ndarray can actually be modified in-place, and the changes will be reflected in the data structure. For heterogeneous data (e.g. some of the DataFrame’s columns are not all the same dtype), this will not be the case. The values attribute itself, unlike the axis labels, cannot be assigned to.

如果DataFrame或Panel包含同类型数据，则ndarray实际上可以就地修改，并且更改将反映在数据结构中。 对于异构数据（例如，某些DataFrame的列不是完全相同的dtype），情况并非如此。 与轴标签不同，无法给值属性本身分配值。

**Note** When working with heterogeneous data, the dtype of the resulting ndarray will be chosen to accommodate all of the data involved. For example, if strings are involved, the result will be of object dtype. If there are only floats and integers, the resulting array will be of float dtype.

**注意** 使用异构数据时，将选择生成的ndarray的dtype以容纳所涉及的所有数据。 例如，如果涉及字符串，则结果将是对象dtype。 如果只有浮点数和整数，则生成的数组将为float dtype。